# Define the local network
acl localnet src 192.168.10.0/24

# Define the domain to block(許可しないdomain)
acl blocked_domain dstdomain .yahoo.co.jp
http_access deny blocked_domain

# Allow access form the local network to all other sites
http_access allow localnet

#Deny all other access
http_access deny all
